config/routes.rb
Rails.application.routes.draw do
  resources :warehouses
  resources :items

  root "warehouses#index"

  get "/warehouses", to: "warehouses#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :warehouse

  validates :item_name, presence: true
  validates :sku, presence: true, uniqueness: true, length: { maximum: 15 }
  validates :quantity ,presence: true ,numericality: { only_integer: true ,greater_than_or_equal_to: 1}
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # fetch all items from the database
  def index
    @items = Item.all
  end

  # find and show a specific item by id
  def show
    @itemes = Item.find(params[:id])
    @name = @item.warehouse.name
  end

  # The new action instantiates a new item, but does not save it.
  # also provides a list of warehouses to link items to warehouse
  def new
    @item = Item.new
    @warehouses = Warehouse.all
  end

  def edit
    @warehouses = Warehouse.all
  end

  # POST /items or /items.json
  # Save the item and selected warehouse to the database
  def create
    @item = Item.new(item_params)
    @warehouses = Warehouse.all

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:item_name, :description, :quantity, :msrp, :wsp, :sku, :warehouse_id)
    end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_warehouse, only: %i[ show edit update destroy ]

  # GET /warehouses or /warehouses.json
  # fetch all warehouses from the database
  def index
    @warehouses = Warehouse.all
  end

  # find and show a specific warehouse by id, the show action calls Warehouse.find
  # and stored in the instance variable @warehouses
  def show
    @warehouses = Warehouse.find(params[:id])
  end

  # GET /warehouses/new
  def new
    @warehouse = Warehouse.new
  end

  # GET /warehouses/1/edit
  def edit
  end

  # POST /warehouses or /warehouses.json
  def create
    @warehouse = Warehouse.new(warehouse_params)

    respond_to do |format|
      if @warehouse.save
        format.html { redirect_to warehouse_url(@warehouse), notice: "Warehouse was successfully created." }
        format.json { render :show, status: :created, location: @warehouse }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /warehouses/1 or /warehouses/1.json
  def update
    respond_to do |format|
      if @warehouse.update(warehouse_params)
        format.html { redirect_to warehouse_url(@warehouse), notice: "Warehouse was successfully updated." }
        format.json { render :show, status: :ok, location: @warehouse }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /warehouses/1 or /warehouses/1.json
  def destroy
    @warehouse.destroy

    respond_to do |format|
      format.html { redirect_to warehouses_url, notice: "Warehouse was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_warehouse
      @warehouse = Warehouse.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def warehouse_params
      params.require(:warehouse).permit(:name, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/items/_form.html.erb
<! The form_with helper method instantiates a form builder. The form_with block calls methods
label and text_field on the form builder to output the appropriate form elements. >

<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :item_name, style: "display: block" %>
    <%= form.text_field :item_name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :msrp, style: "display: block" %>
    <%= form.text_field :msrp %>
  </div>

  <div>
    <%= form.label :wsp, style: "display: block" %>
    <%= form.text_field :wsp %>
  </div>

  <div>
    <%= form.label :sku, style: "display: block" %>
    <%= form.text_field :sku %>
  </div>

  <div>
    <%= form.label :warehouse, style: "display: block" %>
    <%= collection_select(:item, :warehouse_id, @warehouses, :id, :name, {:prompt => true}) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <strong>Item name:</strong>
    <%= item.item_name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= item.description %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= item.quantity %>
  </p>

  <p>
    <strong>Msrp:</strong>
    <%= item.msrp %>
  </p>

  <p>
    <strong>Wsp:</strong>
    <%= item.wsp %>
  </p>

  <p>
    <strong>Sku:</strong>
    <%= item.sku %>
  </p>
  
<! Show the warehouse name that the item is located in >
  <p>
    <strong>Warehouse Location:</strong>
    <%= item.warehouse.name %>
  </p>

</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<! List of all items, link to create new item, create new warehouse, and show each item >
<p style="color: green"><%= notice %></p>

<h1>Inventory</h1>

<div class="grid-container">
  <p>
    <%= link_to "New item", new_item_path %>
  </p>
  <p>
     <%= link_to "Create new warehouse", new_warehouse_path %>
  </p>
<! List of all items >
  <div id="items">
    <% @items.each do |item| %>
      <%= render item %>
      <p>
        <%= link_to "Show this item", item %>
      </p>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit this item", edit_item_path(@item) %> |
  <%= link_to "Back to items", items_path %>
  <%= button_to "Destroy this item", @item, method: :delete %>
</div>

<div>
<%= link_to "Back to warehouses", warehouses_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restock</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/warehouses/_form.html.erb
<%= form_with(model: warehouse) do |form| %>
  <% if warehouse.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(warehouse.errors.count, "error") %> prohibited this warehouse from being saved:</h2>

      <ul>
        <% warehouse.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/warehouses/_warehouse.html.erb
<div id="<%= dom_id warehouse %>">
  <p>
    <strong>Name:</strong>
    <%= warehouse.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= warehouse.address %>
  </p>

</div>

app/views/warehouses/edit.html.erb
<h1>Editing warehouse</h1>

<%= render "form", warehouse: @warehouse %>

<br>

<div>
  <%= link_to "Show this warehouse", @warehouse %> |
  <%= link_to "Back to warehouses", warehouses_path %>
</div>

app/views/warehouses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Warehouses</h1>

<div id="warehouses">
  <% @warehouses.each do |warehouse| %>
    <%= render warehouse %>
    <p>
      <%= link_to "Show this warehouse", warehouse %>
    </p>
  <% end %>
</div>

<p>
  <%= link_to "List all Inventory", items_path %>
</p>

<p>
  <%= link_to "Create new warehouse", new_warehouse_path %>
</p>

<p>
  <%= link_to "Create new item", new_item_path %>
</p>

app/views/warehouses/new.html.erb
<h1>New warehouse</h1>

<%= render "form", warehouse: @warehouse %>

<br>

<div>
  <%= link_to "Back to warehouses", warehouses_path %>
</div>

app/views/warehouses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @warehouse %>

<div>
  <%= link_to "Edit this warehouse", edit_warehouse_path(@warehouse) %> |
  <%= link_to "Back to warehouses", warehouses_path %>

  <%= button_to "Destroy this warehouse", @warehouse, method: :delete %>
</div>